---
- name: Install Torrust
  hosts: torrust
  become: true

  tasks:
    - name: Update apt cache if older than a day
      apt:
        update_cache: yes
        cache_valid_time: 86400

    - name: Install some pre-requisites
      package:
        name:
          - git
          - curl
          - build-essential
          - tmux
          - pkg-config
          - libssl-dev
          - libsqlite3-dev

    # shoutout to https://dentrassi.de/2020/06/17/headless-installation-of-cargo-and-rust/ for the silent install method
    - name: Install Rust
      shell:
        cmd: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
        creates: /root/.cargo/bin/rustc

    - name: Create Torrust folder in /opt/
      file:
        path: /opt/torrust/
        state: directory
        owner: root
        group: root
        mode: 0755

    - name: Check out torrust-tracker
      git:
        repo: https://github.com/torrust/torrust-tracker.git
        dest: /opt/torrust/torrust-tracker

    - name: Build torrust-tracker
      shell:
        cmd: . "$HOME/.cargo/env" && cargo build --release
        chdir: /opt/torrust/torrust-tracker
        creates: /opt/torrust/torrust-tracker/target/release/torrust-tracker

# ./target/release/torrust-tracker
