---
- name: Install Torrust
  hosts: torrust
  become: true
  user: root

  pre_tasks:
    - name: Print Ansible info useful for development
      debug:
        msg:
          - "{{ ansible_distribution }} {{ ansible_distribution_version }}"

  tasks:
    - name: Print debug string
      debug:
        msg: "Test string {{ test_string }}"
